### ISSUE TITLE
[AWS] lambdaでs3からグラフを取得する関数を作成

### ISSUE THREAD

**Issue by yudaisugiyama** [Najah7/Pokemon-Stats-Checker#11]
- [x] API Gateway作成
- [x] lambda作成
- [x] s3作成
- [x] awsコンソールで動作確認

**Comment by yudaisugiyama** [comment]
@Najah7 
boto3からs3のクライアント作成できない(おそらく権限問題)ので、ロールがほしいっす

**Comment by Najah7** [comment]
@yudaisugiyama 

### 念のためのSlackの写し
>数点質問と、提案っす！
> 質問
> - lambda関数の名前なんですか？（管理者権限で探しても見つからなくて。。。）
> - エラーメッセージとかすらなしですか？？
>
> 提案
> - 最初、とりあえず、API Keyを使ってローカルで実装する方向性にします？（ローカルでも8割は実装できると思います。）

[slackのlink](https://12-l9n8939.slack.com/archives/C0626314TAN/p1701324041375599?thread_ts=1701289935.940039&cid=C0626314TAN)

**Comment by yudaisugiyama** [comment]
リージョン東京に修正するの結合試験終わって余裕があったらにさせてください🙇‍♂️
