### ISSUE TITLE
[VSC] fetchした画像を表示する

### ISSUE THREAD

**Issue by umaidashi** [Najah7/Pokemon-Stats-Checker#19]

**Comment by yudaisugiyama** [comment]
@umaidashi 
画像は僕がつくるGETリクエストで取ってくることになると思うんで、どうゆう形式で欲しいか決まり次第教えてください！

**Comment by umaidashi** [comment]
https://12-l9n8939.slack.com/archives/C0626314TAN/p1701412931096829?thread_ts=1701307309.470239&cid=C0626314TAN
