### ISSUE TITLE
[DB] Setup MongoDB

### ISSUE THREAD

**Issue by Najah7** [Najah7/Pokemon-Stats-Checker#20]
本プロジェクトで使う用のMongoDBの用意。

# TODO
- [x] MongoDBを用意する。
- [x] 今あるjsonのデータをMongoDBに突っ込んでみる！

**Comment by Najah7** [comment]
@yudaisugiyama @umaidashi @yusei53 

MongoDBは、用意できたわ！

一応、見てくれたスタンプよろ！
みんなのスタンプついたら、Closeするわ！

#### DBについて補足
512MBまでだったら、無償で使えるっぽい！！
[現在のjsonデータ](https://github.com/Najah7/Pokemon-BaseStats-Checker/blob/develop/vsc-extension/data/pokemons.json)で 56KBだから、全然余裕そうだわ！！

![image](https://github.com/Najah7/Pokemon-BaseStats-Checker/assets/90055003/087d58c9-5cf2-4efc-bcdc-2d461bd9a4c8)

**Comment by umaidashi** [comment]
いいですね！！！
ありがとうございます！
