### ISSUE TITLE
[vsc] 環境変数をいい感じにする

### ISSUE THREAD

**Issue by umaidashi** [Najah7/Pokemon-Stats-Checker#23]
api-keyなどが入る

**Comment by Najah7** [comment]
@umaidashi 
ここ、もう取り組んでます？？
もし、取り組んでなかったら、👇の感じどうですか？

envの定義：https://github.com/Najah7/Pokemon-Stats-Checker/commit/f07fe0b7083455fe1ce914eeb581f2803050f4fe
envの使い方：https://github.com/Najah7/Pokemon-Stats-Checker/commit/7dafdef4682e88d5342ede6c1ed5831221e72a48

**Comment by umaidashi** [comment]
@Najah7 
まだです！取り組んでいただいてありがとうございます！！
セキュリティ的に問題なければ良いと思います！
.envファイルはどこに置くことになりますか？

**Comment by Najah7** [comment]
@umaidashi 
一応、今、自分は`vsc-extension`の配下に置いてます。
`dotenv`仕様的にあんまり気にしなくていいのもあり、とりあえずでテキトウに配置させていただきました。
個人的に今の場所で問題ないのかもな～と思ってます。

**Comment by umaidashi** [comment]
拡張機能として公開、提供する際に問題でてきそうだなーと感じています
拡張機能からapikeyを取られるか分かりませんが、、、
もう少し調査必要そうですね！

@Najah7

**Comment by Najah7** [comment]
@umaidashi 
ですね！
それを踏まえて、[新しいissue](https://github.com/Najah7/Pokemon-Stats-Checker/issues/27)を作りました！
なんで、このissueのスコープは.envを活用しての`config.ts`を作成することにしておきたいです。
それで、[新しいissue](https://github.com/Najah7/Pokemon-Stats-Checker/issues/27)でconfig.tsを修正することで良い感じにクレデンシャルを扱えるように試してみます！！
