### ISSUE TITLE
[vsc] 問題をMongoDBから取得する

### ISSUE THREAD

**Issue by umaidashi** [Najah7/Pokemon-Stats-Checker#26]

**Comment by umaidashi** [comment]
@Najah7 @yudaisugiyama 
問題はどのように出題されるようにしましょうか？？
ランダムor選択or??

**Comment by Najah7** [comment]
@umaidashi @yudaisugiyama 

一応、DB担当の自分は、どっちもにも対応できる実装をしようと思ってます！

### 実装予定のインタフェース
- `readQuestion(): Question`：ランダムで選出
- `readQuestionById(id): Question`：問題をIdで取得
- `readQuestionByName(name): Question`：問題名で問題取得

### 問題オブジェクト（仮案）
👇問題のオブジェクトについて、アドバイスあればほしいっす！
`
interface Question {
    id: number;
    question: string;
    answers: number;
}
`

**Comment by yudaisugiyama** [comment]
とりあえずランダムでいいと思ってます

**Comment by umaidashi** [comment]
@Najah7 
ありがとうございます！
取り組んでいただいてるところ申し訳ないのですが、↓のスレッドで、初期スコープでは問題はとりあえず1問でいいのでは案が出ていて、初期は同じ問題で平等に種族値を測るのはどうかと思っているのですがどうでしょう？？
https://12-l9n8939.slack.com/archives/C0626314TAN/p1701307309470239


> Oidon.
  [5時間前](https://12-l9n8939.slack.com/archives/C0626314TAN/p1701396195628159?thread_ts=1701307309.470239&cid=C0626314TAN)
アルゴリズム問題は判定ができないから本質的ではないかも. 数学関数使った数学的な問題が相性いい気がする.
なるほど、数学は得意じゃないのでお任せしたいです！
問題の難易度と種族値が現状対応しないのがちょっと懸念ですね
難しい問題を解いたからと言っていい種族値になるわけではないので

> yudai sugiyama
  [1時間前](https://12-l9n8939.slack.com/archives/C0626314TAN/p1701412297633449?thread_ts=1701307309.470239&cid=C0626314TAN)
[@Oidon.](https://12-l9n8939.slack.com/team/U06298521EX)
バイアスなしの比較にする場合は問題1つでないとですね. 問題増やすのはスケールしたときの今後の展望に回すというのも１つの手かもしれないです.
